package:
  name: zerorpsanity
  version: !!str 0.1

build:
  entry_points:
    - zerorpc = zerorpc.cli:main
  number: 0

requirements:
  build:
    - python
    - gevent
    - msgpack-python
    - pyzmq

  run:
    - python
    - gevent
    - msgpack-python
    - pyzmq

test:
  # Python imports
  imports:
    - zerorpc

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - zerorpc --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/prakatmac/zerorpc-python/tree/sanitize
  license: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
