package:
  name: zerorpsanity
  version: !!str 0.1

source:
  git_url: git@github.com:prakatmac/zerorpc-python.git
  git_tag: master
  
  #fn: zerorpsanity-0.1.zip
  #url: https://github.com/prakatmac/zerorpc-python/archive/master.zip
  #md5: 916a3d3dce9c5fe658908c45704858bb
#  patches:
   # List any patch files here
   # - fix.patch

build:
  entry_points:
    - zerorpc = zerorpc.cli:main
  number: 2

requirements:
  build:
    - python
    - gevent
    - msgpack-python
    - pyzmq

  run:
    - python
    - gevent
    - msgpack-python
    - pyzmq

test:
  # Python imports
  imports:
    - zerorpc

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - zerorpc --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/prakatmac/zerorpc-python/tree/sanitize
  license: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
